version: '3'
services:
  web:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'production'
      PASSENGER_APP_ENV: 'production'
      DB_DATABASE: 'fat_free_crm_production'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: ''
      DB_HOST: 'db'
      DB_PORT: 5432
      WEB_CONCURRENCY: 2

  db:
    image: postgres:9.5
    restart: always
    ports:
    - '127.0.0.1:5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  gems: {}
